---
- name: Install Apache web server
  yum:
    name: httpd
    state: present

- name: Create HTML file for each VM
  template:
    src: vm_template.html.j2
    dest: "/var/www/html/index.html"
    mode: '0444'
  notify: Restart Apache

- name: Ensure Apache starts on boot
  systemd:
    name: httpd
    enabled: yes
    state: started
