---
- name: Insert text at the end of /etc/rsyslog.conf
  lineinfile:
    path: /etc/rsyslog.conf
    line: "$FileCreateMode 0640"
    insertafter: EOF
  notify: Restart rsyslog

- name: Set permissions on /etc/rsyslog.d
  file:
    path: /etc/rsyslog.d
    owner: root
    group: root
    mode: '0640'
    recurse: yes
  notify: Restart rsyslog

- name: Set permissions on /var/log
  file:
    path: /var/log
    mode: '0775'
  notify: Restart rsyslog

